name: Test Mock API Container Setup

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.7'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependenice
        run: flutter pub get
        run: python -m pip install --upgrade pip
        run: pip install docker

      - name: Test flutter script
        env:
          GITHUB_ACTOR = ${{ gitub.actor }}
          GITHUB_TOKEN = ${{ secrets.GHCR_TOKEN }}
        run: flutter test

